### ISSUE TITLE
Can't set up qbt-cli to work with Basic Auth

### ISSUE THREAD

**Issue by dmilojevic** [fedarovich/qbittorrent-cli#49] opened 2021-03-17 18:26 UTC
Hello.
I am trying to use qbt clie in the following scenario.

qBittorrent web ui is available via Apache reverse proxy with Basic Auth on the url like https://example.mydomain.com/.private/qb/.
I try to set up qbt-cli in the following way:
   qbt network settings -i true
   qbt settings set url https://example.mydomain.com/.private/qb/
   qbt settings set username myaccount
   qbt settings set password

When I try to execute something like qbt server info I get the error message "Response status code does not indicate success: 404 (Not Found)."

When I check Apache access log I see the following
   "GET /version/api HTTP/1.1" 404 3341 "-" "-"
   "POST /api/v2/auth/login HTTP/1.1" 404 424 "-" "-"

I'm confused. Why is qbt cli not trying at least to check the api version in the subdirectory of the url I supplied?

Thanks a lot in advance!

**Comment by zhongfu** [comment] 2023-01-07 18:17
probably a dupe of #30

**Comment by fedarovich** [comment] 2023-12-15 03:16
Yes, it's a duplicate of #30.

**Closed** 2023-12-15 03:23 UTC
